============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.1.3, pluggy-1.0.0
rootdir: /home/iut
collected 0 items / 1 error

==================================== ERRORS ====================================
__________________________ ERROR collecting pytest.py __________________________
import file mismatch:
imported module 'pytest' has this __file__ attribute:
  /home/iut/.local/lib/python3.8/site-packages/pytest
which is not the same as the test file we want to collect:
  /home/iut/pytest.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
=========================== short test summary info ============================
ERROR pytest.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.05s ===============================
